name: base-gp-registrations-mi
on:
  workflow_call:
    inputs:
      environment:
        description: "Which Environment settings to use."
        required: true
        type: string
        default: "dev"

jobs:
  terraform_process:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-skip-session-tagging: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        working-directory: ./stacks/gp-registrations-mi/terraform

      - name: Terraform Init
        id: init
        run: | 
          terraform init -no-color -backend-config="key=${{ secrets.AWS_STATE_S3_KEY }}" \
          -backend-config="bucket=${{ secrets.AWS_STATE_BUCKET }}" \
          -backend-config="dynamodb_table=${{ secrets.AWS_STATE_LOCK_TABLE }}"
        working-directory: ./stacks/gp-registrations-mi/terraform
        shell: bash

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./stacks/gp-registrations-mi/terraform

      - name: Build Lambdas
        run: | 
            ./tasks_github_actions.sh build-lambdas

      - name: Set up Python
        if: github.ref == 'refs/heads/master'
        uses: actions/setup-python@v5

      - name: Make virtual environment
        if: github.ref == 'refs/heads/master'
        with:
          python-version: '3.12'
        run: |
            python3 -m venv ./venv
            ./venv/bin/pip3 install --upgrade pip requests

      - name: Get ODS CSV Files
        if: github.ref == 'refs/heads/master'
        run: |
          PYTHONPATH=$PYTHONPATH:. ./venv/bin/python3 stacks/gp-registrations-mi/scripts/get_latest_ods_csv.py ${{ secrets.TRUD_API_KEY }} ${{ vars.TRUD_API_URL }}

      - name: Setup Terraform variables
        id: vars
        run: |-
          IMAGE_TAG=$(aws ecr describe-images --repository-name ${{ secrets.ECR_REPOSITORY_NAME }} --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]')
          cat > pipeline.auto.tfvars <<EOF
          gp_registrations_mi_image_tag = $IMAGE_TAG
          environment = "${{ inputs.environment }}"
          EOF
        working-directory: ./stacks/gp-registrations-mi/terraform

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color -input=false -var-file="../vars/${{ inputs.environment }}.tfvars" -out "${{ inputs.environment }}.tfplan"
          terraform show -no-color ${{ inputs.environment }}.tfplan > ${{ inputs.environment }}.tfplan.txt
          echo "summary=$(grep -E 'Plan: [0-9]+ to add, [0-9]+ to change, [0-9]+ to destroy\.|No changes\. Your infrastructure matches the configuration\.' ${{ inputs.environment }}.tfplan.txt | sed 's/.*No changes\. Your infrastructure matches the configuration/Plan: no changes/g' | sed 's/.*Plan: //g' | sed 's/\..*//g')" >> $GITHUB_OUTPUT
        working-directory: ./stacks/gp-registrations-mi/terraform
        shell: bash

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve -input=false tf.plan
        working-directory: ./stacks/gp-registrations-mi/terraform

      - name: Add PR comment
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Report for environment: ${{ inputs.environment }}')
            })

            // 2. Prepare format of the comment
            const output = `### Report for environment: ${{ matrix.environment }}

            #### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            <details><summary>Format Output</summary>

            \`\`\`\n
            ${{ steps.fmt.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            <details><summary>Initialization Output</summary>

            \`\`\`\n
            ${{ steps.init.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan (${{ steps.plan.outputs.summary }})</summary>

            \`\`\`\n
            ${{ steps.plan.outputs.stdout }}
            \`\`\`

            </details>`;

            // 3. If we have a comment, update it, otherwise create a new one
            if (botComment) {
              github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })