name: deploy-gp-registrations-mi.yml
on:
  workflow_dispatch:
      inputs:
        environment:
          default: "dev"
          description: "Which environment should this run against"
          required: true
          type: "string"

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  terraform_plan:
    strategy:
      fail-fast: false
      matrix:
        environment: [ dev ]
    uses: ./.github/workflows/base-gp-registrations-mi.yml
    with:
      environment: ${{ matrix.environment }}
    secrets: inherit