name: "PR-terraform-plan"
on:
  pull_request:
    branches:
      - master
    paths:
      - 'stacks/gp-registrations-mi/**'

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  terraform_plan:
    strategy:
      fail-fast: false
      matrix:
        environment: [ dev, prod ]
        terraform_stack: [container-repositories , base-networking, ecs-cluster]
    uses: ./.github/workflows/base-gp-registrations-mi.yml
    with:
      environment: ${{ matrix.environment }}
      working-directory: "stacks/${{ matrix.terraform_stack }}/terraform"
    secrets: inherit


